# Generated by Django 3.0.6 on 2020-06-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=75)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('deck', models.TextField(max_length=2000)),
            ],
            options={
                'db_table': 'game_info',
            },
        ),
    ]
