# Generated by Django 3.0.6 on 2020-06-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_master',
            field=models.CharField(default='', max_length=150),
        ),
    ]
