# Generated by Django 3.0.6 on 2020-06-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_game_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteGame',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=16)),
                ('game_master', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'remote_games',
            },
        ),
    ]
