# Generated by Django 3.0.6 on 2020-08-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remotegame_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotegame',
            name='game_master',
        ),
        migrations.RemoveField(
            model_name='remotegame',
            name='name',
        ),
    ]
