# Generated by Django 3.0.6 on 2020-08-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200817_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotegame',
            name='game_master',
            field=models.CharField(default='', max_length=150),
        ),
    ]
